apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: "broker"
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
    spec:
      restartPolicy: OnFailure
      containers:
      - name: server
        image: vshiva/multi-kafka:latest
        ports:
        - name: broker1
          containerPort: 9092
          hostPort: 9092
          protocol: TCP
        - name: broker2
          containerPort: 9192
          hostPort: 9192
          protocol: TCP
        - name: zk
          containerPort: 2181
          hostPort: 2181
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          exec:
            command:
              - /usr/bin/ready-kafka.sh
          initialDelaySeconds: 15
          periodSeconds: 20